pipeline {
    agent any

    stages {
        stage('Unit Tests - Backend') {
            agent { 
                docker { 
                    image 'snakee/golang-junit:1.21'
                    reuseNode true
                    } 
                }
            steps {
                dir('bugtracker-backend') {
                    sh 'export GOCACHE="$PWD/.cache/go-build"'
                    sh 'export GOMODCACHE="$PWD/.cache/go-mod"'
                    sh 'mkdir -p "$GOCACHE" "$GOMODCACHE"'
                    sh 'go test -v ./...'
                }
            }
        }
    }
}
