pipeline {
    agent any

    stages {
        stage('Unit Tests - Backend') {
            agent {
                docker {
                    image 'snakee/golang-junit:1.21'
                    reuseNode true
                    args '--network=jenkins'
                }
            }
            steps {
                dir('bugtracker-backend') {
                    sh 'export GOCACHE="$PWD/.cache/go-build" export GOMODCACHE="$PWD/.cache/go-mod" mkdir -p "$GOCACHE" "$GOMODCACHE" && go test -v ./...'
                }
            }
        }
    }
}
